#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MICEDroid.Resource", IsApplication=true)]

namespace MICEDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int Accent = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int DarkPrimary = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int Divider = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int LightPrimary = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Primary = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int PrimaryText = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SecondaryText = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int White = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int Connect = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int Container = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Layout = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int MainContent = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int Toolbar = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int Username = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int toolbar = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CallLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Toolbar = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MICETheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
